### ISSUE TITLE
Add the Lesson to the Carpentries Community Developed Lessons listing.

### ISSUE THREAD

**Issue by ilessing** [carpentries-incubator/Reproducible-Publications-with-RStudio#140]
Adding "topics" is how one get's the repo listed on the [community developed lessons](https://carpentries.org/community-lessons/) page.

[Instructions for adding topics](https://carpentries.org/community-lessons/#information-for-lesson-developers)

**Comment by rcurty** [comment]
After the edits and fixing issues we will be submitting it to the Carpentries. We are not sure whether we should submit it to Lab or Incubator. We should reach out to the community to clarify first.  (
Info: [curriculum development handbook](https://cdh.carpentries.org/the-lesson-life-cycle.html#overview-and-definitions)
Torin: Actually, I just saw in the wiki that there is more information on the development tracks right after the development stages info: https://cdh.carpentries.org/the-lesson-life-cycle.html#where-to-start

**Comment by rcurty** [comment]
Closing this after the release of v2.0-quarto.
