### ISSUE TITLE
Ep. 5 - Fix Link to Project Example

### ISSUE THREAD

**Issue by rcurty** [carpentries-incubator/Reproducible-Publications-with-RStudio#208]
Our turn!
We have a repository already prepared for this workshop at https://github.com/UCSBCarpentry/R-repro-pub We are going to use the third option to download a repository from GitHub to work hands on.

replace the link once the project example is transferred to the incubator.

**Comment by ilessing** [comment]
we'll need to update the screenshot too.
[fig/05-github.PNG](https://github.com/carpentries-incubator/Reproducible-Publications-with-RStudio/blob/main/fig/05-github.PNG)

**Comment by rcurty** [comment]
screenshot updated
