### ISSUE TITLE
Maybe use here::here()

### ISSUE THREAD

**Issue by richardjtelford** [carpentries-incubator/Reproducible-Publications-with-RStudio#210]
I had a look at "Good Practices for Managing Projects in RStudio" and wondered whether if would be sensible to introduce here::here() so all paths are relative to the project root rather than using "../" to navigate around the path.

`df <- read.csv("../data/foodchoice_budgetlines.csv", encoding = "UTF-8")`

Some advantages:

 - Don't need to learn ../
 - Can move markdown to different subdirectory level and everything will still work. 
 -  Don't need `knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())` which looks more complicated that here::here()

**Comment by richardjtelford** [comment]
If you want, I can send a pull request.

I have some other suggestions that I will put in a separate issue.

**Comment by rcurty** [comment]
Yes, please go for it!

**Comment by torwhite** [comment]
Thank you! I think we have a tentative plan to convert this lesson to use Quarto.

**Comment by torwhite** [comment]
created a pull requst #212 to address this issue.
