### ISSUE TITLE
Upcoming Manuscript Quarto project type

### ISSUE THREAD

**Issue by Aariq** [carpentries-incubator/Reproducible-Publications-with-RStudio#214]
There's a Manuscript project type currently in pre-release of Quarto that would potentially be really useful for this workshop: https://quarto.org/docs/manuscripts/

**Comment by ilessing** [comment]
Thanks Aariq!  We'll take a look.

**Comment by brunj7** [comment]
Thank you for sharing this @Aariq! We are actively working on the quarto version of this workshop here: https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto  and hope to move it back to the Carpentry incubator in the coming months.

**Comment by rcurty** [comment]
Closing this after the release of v2.0-quarto.
