### ISSUE TITLE
create branch for legacy "rmarkdown" version of the workshop

### ISSUE THREAD

**Issue by ilessing** [carpentries-incubator/Reproducible-Publications-with-RStudio#215]
We intend to update this repo/workshop to instruct on topic of Quarto rather than RMarkdown.

In order to preserve the RMarkdown focused workshop in case anyone want's to conduct a workshop concentrating on Rmarkdown we will make a git branch for the legacy version.  The Readme should mention that the Rmarkdown version will not be maintained/updated as our efforts will be with Quarto/.qmd going forward.

**Comment by rcurty** [comment]
Closing this after the release of v2.0-quarto.
