### ISSUE TITLE
Add to "instructor notes"

### ISSUE THREAD

**Issue by ilessing** [carpentries-incubator/Reproducible-Publications-with-RStudio#92]
see file `_extras/guide.md`

**Comment by rcurty** [comment]
Add GitHub Setup reminders: End of Day, Beginning of Day two, and break before Ep. 5.
Remember that Zotero will only show for those who have it already installed. Ep. 8

**Comment by torwhite** [comment]
We will leave a first pass of instructor notes to the individuals who developed/taught each episode.

**Comment by rcurty** [comment]
Add project folder link to the instructor notes.

**Comment by torwhite** [comment]
Make sure to link the repository for the setup files in the instructor notes as well

**Comment by rcurty** [comment]
Closing this after the release of v2.0-quarto.
